### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by firebluetom** [dogfessional/react-carousel#11]
I tried the demo and cannot switch between images

**Comment by hartzis** [comment]
needs to be a mobile device or in mobile dev mode when on desktop. Need to trigger the touch events.

**Comment by hartzis** [comment]
demo for dev tools mobile mode
![demo for dev tools mobile mode](https://cloud.githubusercontent.com/assets/5378707/18610043/7c15bca6-7cce-11e6-813b-ca7dc3a45fef.gif)
